name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest
        run: >-
          docker run --rm
          -v "${{ github.workspace }}/custom_components:/github/workspace/custom_components:ro"
          ghcr.io/home-assistant/hassfest
          --integration-path /github/workspace/custom_components/wiserlink_mpi
